// <auto-generated />
namespace BeautifulDestinations2._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addRating : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addRating));
        
        string IMigrationMetadata.Id
        {
            get { return "202001261350576_addRating"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
